:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
staging:
  :concurrency: 10
development:
  :concurrency: 20
production:
  :concurrency: 20
:queues:
  - default
  - [myqueue, 2]
